sudo: required

language: C

services:
- docker

script:
- docker run -v"$(pwd):/root/nanvix/hal" -p4567:4567 nanvix/toolchain-openrisc:latest /bin/sh -c "cd /root/nanvix/hal && export TARGET=qemu-openrisc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && make distclean  && make all"
- docker run -v"$(pwd):/root/nanvix/hal" -p4567:4567 nanvix/toolchain-i486:latest /bin/sh -c "cd /root/nanvix/hal && export TARGET=qemu-x86 && export TOOLCHAIN_DIR=/root/toolchain/i486/bin && make distclean && make all"
- docker run -v"$(pwd):/root/nanvix/hal" -p4567:4567 nanvix/toolchain-riscv32:latest /bin/sh -c "cd /root/nanvix/hal && export TARGET=qemu-riscv32 && export TOOLCHAIN_DIR=/root/toolchain/riscv32/bin && make distclean && make all"

notifications:
  slack: nanvix:31ePVjsrXynUajPUDqy6I0hp
